title: "Tarctic's life"
author: Tarctic
email: zainab7@amityonline.com
theme: minimia
description: > # this means to ignore newlines until "baseurl:"
  Water good

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/Tarctic # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
